trigger:
- main

variables:
  TF_VERSION: '1.5.0'
  WORKING_DIR: 'Env/dev'
  SERVICE_CONNECTION: 'azure-terraform-conn'

stages:

# ================= INIT =================
- stage: Init
  displayName: "Terraform Init"

  jobs:
  - job: InitJob
    pool:
      vmImage: ubuntu-latest

    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(TF_VERSION)

    - task: TerraformTaskV4@4
      displayName: "Terraform Init"
      inputs:
        provider: azurerm
        command: init
        workingDirectory: 'Env/dev'
        backendServiceArm: $(SERVICE_CONNECTION)
        backendAzureRmResourceGroupName: 'jenkins-rg'
        backendAzureRmStorageAccountName: 'devbackendrg'
        backendAzureRmContainerName: 'mybackup'
        backendAzureRmKey: 'dev.tfstate'

# ================= PLAN =================
- stage: Plan
  displayName: "Terraform Plan"
  dependsOn: Init

  jobs:
  - job: PlanJob
    pool:
      vmImage: ubuntu-latest

    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(TF_VERSION)

    - script: |
        cd Env/dev

        echo "=== FILES ==="
        ls -la

        echo "=== TFVARS ==="
        cat terraform.tfvars

        terraform init

        terraform plan -var-file="terraform.tfvars" -out=tfplan
      displayName: "Terraform Plan (FIXED)"

# ================= APPLY =================
- stage: Apply
  displayName: "Terraform Apply"
  dependsOn: Plan
  condition: succeeded()

  jobs:
  - job: ApplyJob
    pool:
      vmImage: ubuntu-latest

    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(TF_VERSION)

    - script: |
        cd Env/dev
        terraform apply -auto-approve tfplan
      displayName: "Terraform Apply"