trigger:
- main

stages:

- stage: Init
  jobs:
  - job: InitJob
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.5.0'

    - script: |
        terraform version
        which terraform
      displayName: Verify Terraform